// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.0
// source: tsdecoder/internal.proto

package tsdecoder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalTimeSeriesData struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	StartTimestampNanos int64                       `protobuf:"varint,1,opt,name=start_timestamp_nanos,json=startTimestampNanos,proto3" json:"start_timestamp_nanos,omitempty"`
	SampleDurationNanos int64                       `protobuf:"varint,2,opt,name=sample_duration_nanos,json=sampleDurationNanos,proto3" json:"sample_duration_nanos,omitempty"`
	Samples             []*InternalTimeSeriesSample `protobuf:"bytes,3,rep,name=samples,proto3" json:"samples,omitempty"`
	Offset              []int32                     `protobuf:"varint,4,rep,packed,name=offset,proto3" json:"offset,omitempty"`
	Last                []float64                   `protobuf:"fixed64,5,rep,packed,name=last,proto3" json:"last,omitempty"`
	Count               []uint32                    `protobuf:"varint,6,rep,packed,name=count,proto3" json:"count,omitempty"`
	Sum                 []float64                   `protobuf:"fixed64,7,rep,packed,name=sum,proto3" json:"sum,omitempty"`
	Max                 []float64                   `protobuf:"fixed64,8,rep,packed,name=max,proto3" json:"max,omitempty"`
	Min                 []float64                   `protobuf:"fixed64,9,rep,packed,name=min,proto3" json:"min,omitempty"`
	First               []float64                   `protobuf:"fixed64,10,rep,packed,name=first,proto3" json:"first,omitempty"`
	Variance            []float64                   `protobuf:"fixed64,11,rep,packed,name=variance,proto3" json:"variance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InternalTimeSeriesData) Reset() {
	*x = InternalTimeSeriesData{}
	mi := &file_tsdecoder_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTimeSeriesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTimeSeriesData) ProtoMessage() {}

func (x *InternalTimeSeriesData) ProtoReflect() protoreflect.Message {
	mi := &file_tsdecoder_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTimeSeriesData.ProtoReflect.Descriptor instead.
func (*InternalTimeSeriesData) Descriptor() ([]byte, []int) {
	return file_tsdecoder_internal_proto_rawDescGZIP(), []int{0}
}

func (x *InternalTimeSeriesData) GetStartTimestampNanos() int64 {
	if x != nil {
		return x.StartTimestampNanos
	}
	return 0
}

func (x *InternalTimeSeriesData) GetSampleDurationNanos() int64 {
	if x != nil {
		return x.SampleDurationNanos
	}
	return 0
}

func (x *InternalTimeSeriesData) GetSamples() []*InternalTimeSeriesSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *InternalTimeSeriesData) GetOffset() []int32 {
	if x != nil {
		return x.Offset
	}
	return nil
}

func (x *InternalTimeSeriesData) GetLast() []float64 {
	if x != nil {
		return x.Last
	}
	return nil
}

func (x *InternalTimeSeriesData) GetCount() []uint32 {
	if x != nil {
		return x.Count
	}
	return nil
}

func (x *InternalTimeSeriesData) GetSum() []float64 {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *InternalTimeSeriesData) GetMax() []float64 {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *InternalTimeSeriesData) GetMin() []float64 {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *InternalTimeSeriesData) GetFirst() []float64 {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *InternalTimeSeriesData) GetVariance() []float64 {
	if x != nil {
		return x.Variance
	}
	return nil
}

type InternalTimeSeriesSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         uint32                 `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Sum           float64                `protobuf:"fixed64,7,opt,name=sum,proto3" json:"sum,omitempty"`
	Max           float64                `protobuf:"fixed64,8,opt,name=max,proto3" json:"max,omitempty"`
	Min           float64                `protobuf:"fixed64,9,opt,name=min,proto3" json:"min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalTimeSeriesSample) Reset() {
	*x = InternalTimeSeriesSample{}
	mi := &file_tsdecoder_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalTimeSeriesSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalTimeSeriesSample) ProtoMessage() {}

func (x *InternalTimeSeriesSample) ProtoReflect() protoreflect.Message {
	mi := &file_tsdecoder_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalTimeSeriesSample.ProtoReflect.Descriptor instead.
func (*InternalTimeSeriesSample) Descriptor() ([]byte, []int) {
	return file_tsdecoder_internal_proto_rawDescGZIP(), []int{1}
}

func (x *InternalTimeSeriesSample) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InternalTimeSeriesSample) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *InternalTimeSeriesSample) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *InternalTimeSeriesSample) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *InternalTimeSeriesSample) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

var File_tsdecoder_internal_proto protoreflect.FileDescriptor

const file_tsdecoder_internal_proto_rawDesc = "" +
	"\n" +
	"\x18tsdecoder/internal.proto\x12\ttsdecoder\"\x89\x03\n" +
	"\x16InternalTimeSeriesData\x122\n" +
	"\x15start_timestamp_nanos\x18\x01 \x01(\x03R\x13startTimestampNanos\x122\n" +
	"\x15sample_duration_nanos\x18\x02 \x01(\x03R\x13sampleDurationNanos\x12=\n" +
	"\asamples\x18\x03 \x03(\v2#.tsdecoder.InternalTimeSeriesSampleR\asamples\x12\x1a\n" +
	"\x06offset\x18\x04 \x03(\x05B\x02\x10\x01R\x06offset\x12\x16\n" +
	"\x04last\x18\x05 \x03(\x01B\x02\x10\x01R\x04last\x12\x18\n" +
	"\x05count\x18\x06 \x03(\rB\x02\x10\x01R\x05count\x12\x14\n" +
	"\x03sum\x18\a \x03(\x01B\x02\x10\x01R\x03sum\x12\x14\n" +
	"\x03max\x18\b \x03(\x01B\x02\x10\x01R\x03max\x12\x14\n" +
	"\x03min\x18\t \x03(\x01B\x02\x10\x01R\x03min\x12\x18\n" +
	"\x05first\x18\n" +
	" \x03(\x01B\x02\x10\x01R\x05first\x12\x1e\n" +
	"\bvariance\x18\v \x03(\x01B\x02\x10\x01R\bvariance\"~\n" +
	"\x18InternalTimeSeriesSample\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05count\x18\x06 \x01(\rR\x05count\x12\x10\n" +
	"\x03sum\x18\a \x01(\x01R\x03sum\x12\x10\n" +
	"\x03max\x18\b \x01(\x01R\x03max\x12\x10\n" +
	"\x03min\x18\t \x01(\x01R\x03minB/Z-github.com/cockroachlabs/transcoder/tsdecoderb\x06proto3"

var (
	file_tsdecoder_internal_proto_rawDescOnce sync.Once
	file_tsdecoder_internal_proto_rawDescData []byte
)

func file_tsdecoder_internal_proto_rawDescGZIP() []byte {
	file_tsdecoder_internal_proto_rawDescOnce.Do(func() {
		file_tsdecoder_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsdecoder_internal_proto_rawDesc), len(file_tsdecoder_internal_proto_rawDesc)))
	})
	return file_tsdecoder_internal_proto_rawDescData
}

var file_tsdecoder_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tsdecoder_internal_proto_goTypes = []any{
	(*InternalTimeSeriesData)(nil),   // 0: tsdecoder.InternalTimeSeriesData
	(*InternalTimeSeriesSample)(nil), // 1: tsdecoder.InternalTimeSeriesSample
}
var file_tsdecoder_internal_proto_depIdxs = []int32{
	1, // 0: tsdecoder.InternalTimeSeriesData.samples:type_name -> tsdecoder.InternalTimeSeriesSample
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tsdecoder_internal_proto_init() }
func file_tsdecoder_internal_proto_init() {
	if File_tsdecoder_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsdecoder_internal_proto_rawDesc), len(file_tsdecoder_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tsdecoder_internal_proto_goTypes,
		DependencyIndexes: file_tsdecoder_internal_proto_depIdxs,
		MessageInfos:      file_tsdecoder_internal_proto_msgTypes,
	}.Build()
	File_tsdecoder_internal_proto = out.File
	file_tsdecoder_internal_proto_goTypes = nil
	file_tsdecoder_internal_proto_depIdxs = nil
}
